# Generated by Django 4.2.16 on 2024-10-02 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='rental_peroid',
            new_name='rental_period',
        ),
    ]
