# Generated by Django 4.2.16 on 2024-10-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_book_totale_rental'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='totale_rental',
            new_name='total_rental',
        ),
    ]
