# Generated by Django 4.2.16 on 2024-10-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_rename_totale_rental_book_total_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
